sudo: false
language: node_js
node_js:
  - '0.10'
  - '0.12'
  - 'iojs'
cache:
  directories:
    - node_modules
env:
  global:
    - GH_USER_NAME: wilmoore
    - GIT_AUTHOR_NAME: "TravisCI"
    - GIT_AUTHOR_EMAIL: "noreply@travis-ci.org"
