sudo: false
language: node_js
node_js:
  - '0.12'
  - 'iojs'
before_script:
  - git remote rm origin
  - git remote add origin https://github.com/wilmoore/sprout-commonjs-lib.git
  - git config --global user.name "Wil Moore III"
  - git config --global user.email "wil.moore@wilmoore.com"
  - git config --global github.user "wilmoore"
before_install:
  - npm install -g npm@latest
