sudo: false
language: node_js
node_js:
  - '0.10'
  - '0.12'
  - 'iojs'
cache:
  directories:
    - node_modules
before_script:
  - git remote rm origin
  - git remote add origin https://github.com/wilmoore/sprout-commonjs-lib.git
  - git config --global github.user "wilmoore"
  - git config --global user.email "wil.moore@wilmoore.com"
  - git config --global user.name "Wil Moore III"
